# Generated by Django 4.0.1 on 2023-10-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0002_baseuser_delete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='id',
            new_name='user_id',
        ),
    ]
