# Generated by Django 4.0.1 on 2023-10-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0003_rename_id_baseuser_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='last_login',
        ),
    ]
